---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tseries)
library(forecast)
library(plotly)
library(dplyr)
library(readxl)
library(TSstudio)

```

# Simulación modelos

## Punto 1

```{r}
set.seed(1234)

k = 500  # Number of time series
n = 1000 # Time for each time serie

epsilon <- matrix(rnorm(k*n, mean = 0, sd = 1), nrow=k, ncol=n)
y1 <- matrix(, nrow=k, ncol=n)

for(i in 1:k){
  y1[i,1] <- 0
  y1[i,2] <- 0
}


for(i in 1:k){
  for(t in 3:n){ 
    y1[i,t] <- 0.5*y1[i,t-1] +y1[i,t-1] -0.5*y1[i,t-2] + epsilon[i,t] + 0.3* epsilon[i,t-1]
  }
}

par(mfrow=c(1,1))
matplot(t(y1), type = "l", xlab="Time", ylab="yt")
```

```{r}
adf.test(y1[1,])
adf.test(y1[10,])

# Phillips-Perron test
pp.test(y1[1,])
pp.test(y1[10,])

# KPSS test
kpss.test(y1[1,])
kpss.test(y1[10,])
```

```{r}
y1_diff <- matrix(, nrow=k, ncol=n-1)

for(i in 1:k){
  y1_diff[i,] <- diff(y1[i,]) 
}


adf.test(y1_diff[1,])
adf.test(y1_diff[10,])

# Phillips-Perron test
pp.test(y1_diff[1,])
pp.test(y1_diff[10,])

# KPSS test
kpss.test(y1_diff[1,])
kpss.test(y1_diff[10,])
```

```{r}
par(mfrow=c(2,2))
acf(y1_diff[2,])
acf(y1_diff[4,])
acf(y1_diff[8,])
acf(y1_diff[10,])


```

```{r}

par(mfrow=c(2,2))
pacf(y1_diff[2,])
pacf(y1_diff[4,])
pacf(y1_diff[8,])
pacf(y1_diff[10,])
```

```{r}

best_order2 <- c(0, 0, 0)
best_bic2 <- Inf
for (i in 0:5) for (j in 0:5) {
  fit_bic2 <- BIC(arima(y1_diff[1,], order = c(i, 0, j)))
  if (fit_bic2 < best_bic2) {
    best_order2 <- c(i, 0, j)
    best_bic2 <- fit_bic2
  }
}

```

```{r}
best_order2
best_bic2
```

```{r}


best_order2 <- c(0, 0, 0)
best_bic2 <- Inf
for (i in 0:5) for (j in 0:5)  {
  fit_bic2 <- BIC(arima(y1[1,], order = c(i, 1, j)))
  if (fit_bic2 < best_bic2) {
    best_order2 <- c(i, 1, j)
    best_bic2 <- fit_bic2
  }
}


```

```{r}
best_order2
best_bic2
```

```{r}
auto.arima(y1[1,])
```

## Punto 2

```{r}
set.seed(1234)
omega <- 0.06
alpha1 <- 0.2
beta1 <- 0.5
N <- 1000000
et <- rnorm(N,1,1)
rt <- rep(0, N)
sigmat <- rep(0, N)
for (i in 2:N) {
  sigmat[i] <- omega + alpha1 * (rt[i - 1]) + beta1 * sigmat[i-1]
  rt[i] <- et[i] * sqrt(sigmat[i])
}




```

```{r}
par(mfrow=c(1,1))
plot(rt, type = "l", xlab="Time", ylab="yt")
```

```{r}
par(mfrow=c(1,2))
acf(rt)
acf(rt^2)
```

```{r}
var(rt)
```

```{r}
omega/(1-alpha1-beta1)
```

```{r}
library(tseries)
rt.garch <- garch(rt, grad = "numerical", trace = FALSE)
confint(rt.garch)

```

## 

### Punto 3

```{r}
set.seed(1234)
gamma <- 0.1
beta <- 0.2
N=1000
iid_normal_vars <- matrix(rnorm(2*N, mean = 0, sd = 1), nrow=2, ncol=N)
et <- iid_normal_vars[1,]
zeta <- iid_normal_vars[2,]
alphat <- rep(0, N)
yt <- rep(0, N)
for (i in 2:N) {
  alphat[i] <- gamma + beta * alphat[i - 1] + zeta[i]
  yt[i] <- alphat[i] * yt[i - 1] + et[i]
}
```

```{r}
par(mfrow=c(1,1))
plot(alphat, type = "l", xlab="Time", ylab="alphat")
```

```{r}
par(mfrow=c(1,1))
plot(yt, type = "l", xlab="Time", ylab="yt")
```

```{r}
par(mfrow=c(1,2))
acf(yt)
pacf(yt)
```
